# Generated by Django 4.1.7 on 2023-04-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=0, verbose_name='Версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('groups', models.ManyToManyField(to='accounts.sitegroup', verbose_name='Группы менеджеров')),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='менеджеры')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=0, verbose_name='Версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=0, verbose_name='Версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('is_technical', models.BooleanField(verbose_name='Является ли техническим звеном')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Номер в цепочке')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.actor', verbose_name='Актор')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.chain', verbose_name='Цепочка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=0, verbose_name='Версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('body', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.chain', verbose_name='Цепочка')),
                ('current_chain_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.chainlink', verbose_name='Текущий этап')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chain',
            name='accept_chain_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_chain_links', to='idea.chainlink', verbose_name='Звено для принятых'),
        ),
        migrations.AddField(
            model_name='chain',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='chain',
            name='reject_chain_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_chain_links', to='idea.chainlink', verbose_name='Звено для отклоненных'),
        ),
    ]
