# Generated by Django 4.1.7 on 2023-04-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='groups',
            field=models.ManyToManyField(blank=True, to='accounts.sitegroup', verbose_name='Группы менеджеров'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='менеджеры'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.actor', verbose_name='Актор'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.chain', verbose_name='Цепочка'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер в цепочке'),
        ),
    ]
